### ISSUE TITLE
Pre-commit script gives an error with new setup

### ISSUE THREAD

**Issue by sdl60660** [ft-interactive/starter-kit#308]
Pre-commit script is giving me the following error across projects (and on starter-kit template). I've had to comment it out on projects, but hopefully we can resolve the root of it:

` /Users/sam.learner/.npm/_npx/15f9efe159c89f49/node_modules/pretty-quick/dist/isSupportedExtension.js:12
  ..._prettier.resolveConfig.sync(file, {
                             ^

TypeError: _prettier.resolveConfig.sync is not a function
    at /Users/sam.learner/.npm/_npx/15f9efe159c89f49/node_modules/pretty-quick/dist/isSupportedExtension.js:12:30
    at Array.filter (<anonymous>)
    at _default (/Users/sam.learner/.npm/_npx/15f9efe159c89f49/node_modules/pretty-quick/dist/index.js:53:157)
    at Object.<anonymous> (/Users/sam.learner/.npm/_npx/15f9efe159c89f49/node_modules/pretty-quick/bin/pretty-quick.js:17:27)
    at Module._compile (node:internal/modules/cjs/loader:1275:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1329:10)
    at Module.load (node:internal/modules/cjs/loader:1133:32)
    at Module._load (node:internal/modules/cjs/loader:972:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12)
    at node:internal/main/run_main_module:23:47

Node.js v19.7.0
husky - pre-commit hook exited with code 1 (error)`

**Comment by aendra-rininsland** [comment]
Seems related to this https://stackoverflow.com/a/76628485
